"""
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	 By starting with 1 and 2, the first 10 terms will be:
		
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	 find the sum of the even-valued terms.
"""

def even_fibonacci_sum(a):
	f_1 = 1
	f_2 = 2
	
	limit = a
	
	# given f_2 defined as 2
	output = 2
	
	f_3 = f_1 + f_2
	
	while f_3 <= limit:
		
		if f_3%2 == 0:
			output += f_3
	
		f_1 = f_2
		f_2 = f_3
	
		f_3 = f_1 + f_2

	return output

print(even_fibonacci_sum(4000000))